Hw2 task6 smallestnumber
illided/SPbSUHomework pull request #12
Opened 2019-10-08 18:13 UTC by illided

Поменял ветку и теперь все более менее цивильно

2019-10-22 11:08 UTC, jzuken requested changes

2019-10-22 11:08 UTC, jzuken commented on hw2/task_6_smallest_number/main.c
> +        while(numerals[digitNumber] != 0)
пробел

2019-11-07 13:36 UTC, SpirinEgor requested changes

2019-11-07 13:36 UTC, SpirinEgor commented on hw2/task_6_smallest_number/.gitignore
> +cmake-build-debug/*
Этот .gitignore надо объеденить с .gitignore в корне репозитория, тогда не придётся делать по отдельному на каждую домашку

2019-11-07 13:36 UTC, SpirinEgor commented on hw2/task_6_smallest_number/main.c
> +        }
Это можно записать одним циклом `for`
`for (int digitNumber = 0; digitNumber < 10; ++digitNumber)`

2019-12-08 15:46 UTC, merged