task 5.1
illided/SPbSUHomework pull request #16
Opened 2019-10-22 11:47 UTC by illided

2019-11-28 09:40 UTC, SpirinEgor requested changes

2019-11-28 09:40 UTC, SpirinEgor commented on hw5/task1_sort_station/main.c
> +int priorities[4]  = { 1,   1,   2,   2};
Эти массивы используются только в функции `getPriority`, поэтому лучше их объявить там. Надо избегать глобальных переменных

2019-11-28 09:40 UTC, SpirinEgor commented on hw5/task1_sort_station/main.c
> +        inputIsCorrect = inputIsCorrect + isdigit(input[currentChar]) + (input[currentChar] == '(') +
Наверное, вместо `+` должно стоять `&&`, всё-таки логическое выражение

2019-11-28 09:40 UTC, SpirinEgor commented on hw5/task1_sort_station/main.c
> +            while ((peek(specialCharsStack) != '(') &&(currentOperationPriority <= getPriority(peek(specialCharsStack))))
Пробела не хватает

2019-11-28 09:40 UTC, SpirinEgor commented on hw5/task1_sort_station/main.c
> +            while ((peek(specialCharsStack) != '(') &&(currentOperationPriority <= getPriority(peek(specialCharsStack))))
Ну и можно строчку на 2 разбить

2019-11-28 09:40 UTC, SpirinEgor commented on hw5/task1_sort_station/main.c
> +        inputIsCorrect = inputIsCorrect + isdigit(input[currentChar]) + (input[currentChar] == '(') +
Ну и можно весь этот блок вынести в отдельную функцию, где завести массив `allowedCharacters` и проверить, что символ в нём находится

2019-12-01 20:59 UTC, fefaleksey approved these changes
ok

2019-12-02 10:56 UTC, jzuken requested changes

2019-12-02 10:56 UTC, jzuken commented on hw5/task1_sort_station/main.c
> +    int numOfOperations = 4;
а почему не константа?

2019-12-02 10:56 UTC, jzuken commented on hw5/task1_sort_station/main.c
> +    char operations[4] = {'+', '-', '*', '/'};
ну раз константу объявил, то чего бы ей не пользоваться?

2019-12-02 10:56 UTC, jzuken commented on hw5/task1_sort_station/main.c
> +char *convertRpn(char *input)
что за rpn? не надо таких криптосокращений

2019-12-02 10:56 UTC, jzuken commented on hw5/task1_sort_station/main.c
> +             * send it to the output*/
а есть какой-то тайный смысл, чтобы разбивать этот коммент на две строки?

2019-12-02 10:56 UTC, jzuken commented on hw5/task1_sort_station/main.c
> +            if (!tryToHandleCloseBracket(&outputLength, specialCharsStack, output))
неудачная комбинация имени функции и возвращаемого значения даёт странный и непонятный код на выходе

2019-12-02 10:56 UTC, jzuken commented on hw5/task1_sort_station/main.c
> +    for (int currentChar = 0; input[currentChar] != '\0'; currentChar++)
хорошо бы вынести весь код, относящийся к сортировочной станции, в отдельный модуль

2019-12-02 11:03 UTC, fefaleksey commented on hw5/task1_sort_station/main.c
> +    char operations[4] = {'+', '-', '*', '/'};
Тогда не получится написать = {'+', '-', '*', '/'}; :)

2019-12-18 10:16 UTC, SpirinEgor commented
Для ввода `1` падают ошибки в валгринде с неправильным чтением и записью значения

2019-12-22 05:56 UTC, merged