Hw6 task3 tree
illided/SPbSUHomework pull request #21
Opened 2019-11-13 16:49 UTC by illided

2019-12-08 17:16 UTC, jzuken requested changes

2019-12-08 17:16 UTC, jzuken commented on hw6/task3_tree/main.c
> +    printf("\nI can check if there a something in the tree!\nAsk me about some number:\n");
ну это фиговый интерактивный режим, хочется делать с деревом все операции

2019-12-08 17:16 UTC, jzuken commented on hw6/task3_tree/basic_tree.h
> +//return empty tree
про это уже писал

2019-12-19 11:50 UTC, SpirinEgor requested changes

2019-12-19 11:50 UTC, SpirinEgor commented on hw6/task3_tree/basic_tree.c
> +    return false;
`return !isEmpty(tree) && (findNodeWithValue(value, tree->root) != Null)`

2019-12-19 11:50 UTC, SpirinEgor commented on hw6/task3_tree/basic_tree.h
> +//return empty tree
Но не исправлено...

2019-12-19 11:50 UTC, SpirinEgor commented on hw6/task3_tree/main.c
> +            case 1:
для каждого case надо ставить {}

2019-12-20 17:37 UTC, SpirinEgor reviewed
Разберись с комментариями в хедере, тебе уже 2 раза оставляли там комментарии. Они идут в разнобой, хочется в одинаковом стиле.

2019-12-23 21:29 UTC, merged