Hw7 task1 balanced tree
illided/SPbSUHomework pull request #26
Opened 2019-11-30 10:28 UTC by illided

2019-12-08 15:54 UTC, jzuken requested changes

2019-12-08 15:54 UTC, jzuken commented on hw7/task1_balanced_tree/main.c
> +    burnTheTree(tree);
это всё здорово, но где интерактивный режим?

2019-12-08 15:54 UTC, jzuken commented on hw7/task1_balanced_tree/auto_balancing_tree.h
> +// add value to the tree
комментарий обычно пишут перед комментируемой сущностью, а не после

2019-12-08 15:54 UTC, jzuken commented on hw7/task1_balanced_tree/auto_balancing_tree.h
> +bool isInTree(int value, Tree* tree);
лучше сначала дерево, а потом уже значение

2019-12-10 11:52 UTC, SpirinEgor requested changes

2019-12-10 11:52 UTC, SpirinEgor commented on hw7/task1_balanced_tree/auto_balancing_tree.c
> +}
`max(a, b) + 1`

2019-12-10 11:52 UTC, SpirinEgor commented on hw7/task1_balanced_tree/auto_balancing_tree.c
> +    return false;
`return findNodeWithValue(...) != NULL`

2019-12-19 12:36 UTC, SpirinEgor requested changes

2019-12-19 12:36 UTC, SpirinEgor commented on hw7/task1_balanced_tree/main.c
> +            case 1:
Для case тоже надо {}

2019-12-19 12:36 UTC, SpirinEgor commented on hw7/task1_balanced_tree/auto_balancing_tree.h
> +//return empty tree
У нас нет стайлгайда на комменты, поэтому можно писать в любом стиле.
Но давай делать это единообразно, у тебя где-то после `//` есть пробел, а где-то нет

2019-12-20 17:41 UTC, SpirinEgor requested changes

2019-12-20 17:41 UTC, SpirinEgor commented on hw7/task1_balanced_tree/auto_balancing_tree.h
> +//print the tree values in descending order
а тут? надо все комментарии поправить

2019-12-25 11:06 UTC, merged