Created a rough solution to 9.1
illided/SPbSUHomework pull request #28
Opened 2019-12-09 19:35 UTC by illided

2019-12-10 11:36 UTC, jzuken commented
Enter floating point number:
--1
Input is correct

2019-12-10 11:37 UTC, jzuken requested changes

2019-12-10 11:37 UTC, jzuken commented on hw9/task1_regexp/main.c
> +        case 1:
а давай придумаем для этих состояний какой-нибудь enum с говорящими именами состояний. а то так же отлаживать невозможно

2019-12-19 13:05 UTC, SpirinEgor commented
У тебя тесты стиль кода упали, чего не поправляешь то?)

2019-12-19 13:07 UTC, SpirinEgor requested changes

2019-12-19 13:07 UTC, SpirinEgor commented on hw9/task1_regexp/main.c
> +        case initial:
case надо выделять через {}

2019-12-23 21:31 UTC, jzuken commented
<img width="694" alt="Screenshot 2019-12-24 at 00 30 55" src="https://user-images.githubusercontent.com/705678/71381451-a76e0d00-25e4-11ea-98aa-b6a8fb3fe07b.png">

ну как-то грустно

2019-12-25 11:09 UTC, merged