added a solution for task 1 in homework 2
illided/SPbSUHomework pull request #6
Opened 2019-09-28 10:40 UTC by illided

2019-10-22 10:50 UTC, jzuken requested changes

2019-10-22 10:50 UTC, jzuken commented on hw2/task_1_number_splitting/main.c
> +    int *array = malloc((number + 1) * sizeof(int));
память выделил, а освобождать кто будет?

2019-11-07 13:31 UTC, SpirinEgor commented
gitignore делают общим на весь репозиторий, а не по одному на каждую папку.

2019-11-19 11:19 UTC, SpirinEgor requested changes

2019-11-19 11:19 UTC, SpirinEgor commented on hw2/task_1_number_splitting/main.c
> +int main() {
Скобочки начинаются со следующей строки

2019-12-08 13:14 UTC, merged