Hw 2 task 3 cows and bulls
illided/SPbSUHomework pull request #7
Opened 2019-09-29 12:26 UTC by illided

2019-10-08 11:53 UTC, jzuken requested changes

2019-10-08 11:53 UTC, jzuken commented on hw2/task_2_cows_and_bulls/main.c
> +        int *guess = malloc(spaceForGuess * sizeof(int));
а её правда надо выделять на каждой итерации?

2019-10-09 06:25 UTC, illided commented
Оставил значение showTheAnswer как true чтобы удобнее было проверять и отлаживать

2019-10-09 06:39 UTC, illided commented
Хотя наверное пусть лучше будет false

2019-10-09 06:40 UTC, illided commented
(from true to false) конечно же

2019-10-22 11:23 UTC, jzuken requested changes

2019-10-22 11:23 UTC, jzuken commented on hw2/task_2_cows_and_bulls/.gitignore
> +*.o
этот файл надо в корень репозитория положить один раз, не надо его в каждую домашку пихать

2019-10-22 11:23 UTC, jzuken commented on hw2/task_2_cows_and_bulls/main.c
> +    for (int i = 1; i < numOfDigits; i++)
генерацию вполне стоило бы вынести в отдельную функцию

2019-11-07 13:29 UTC, SpirinEgor reviewed
.gitignore должен быть глобальным на весь репозиторий, а не в каждой папке по отдельному.

2019-11-19 11:28 UTC, SpirinEgor requested changes

2019-11-19 11:28 UTC, SpirinEgor commented on hw2/task_2_cows_and_bulls/main.c
> +const int maxSize = 80;  // maxSize > 11 because user can enter the bigger string
У нас нет какого-то определенного стайлгайда для комментов, поэтому просто делайте их однообразными. То есть одинаковое число пробелов до и после `//`

2019-11-19 11:28 UTC, SpirinEgor commented on hw2/task_2_cows_and_bulls/main.c
> +int main() {
Фигурная скобка со следующей строчки

2019-11-19 11:28 UTC, SpirinEgor commented on hw2/task_2_cows_and_bulls/main.c
> +int raiseToThePower(int number, int power)
Вроде как не используется

2019-12-08 15:43 UTC, merged