added a solution for task 3.2
illided/SPbSUHomework pull request #9
Opened 2019-10-03 17:25 UTC by illided

2019-10-15 11:41 UTC, jzuken requested changes

2019-10-15 11:41 UTC, jzuken commented on hw3/task2_empty_strings/file.txt
> +nothing
если сюда добавить строку, состоящую из двух табов и пробела, оно выдаёт 6

2019-10-15 11:41 UTC, jzuken commented on hw3/task2_empty_strings/main.c
> +    char* input = malloc(sizeof(char) * maxSize);
а удалить бы ещё неплохо

2019-10-26 15:01 UTC, illided commented on hw3/task2_empty_strings/file.txt
> +nothing
Проверил у себя и все подсчитывается верно. Скиньте пожалуйста файл txt и скрин работы программы

2019-11-07 14:05 UTC, SpirinEgor requested changes

2019-11-07 14:05 UTC, SpirinEgor commented on hw3/task2_empty_strings/main.c
> +    for (int i = 0; i < strlen(input); i++)
`strlen` лучше выносить в отдельную переменную, так как иначе считается на каждой итерации

2019-12-10 11:04 UTC, jzuken commented
добавил строку из двух табов и пробела, счётчик поменялся

2019-12-23 21:26 UTC, merged